---
deployment:
  tasks:
    - export DEPLOYPATH=/home/Montessoridz/adalen-dz.com/
    - /usr/bin/rsync -rlptDv --exclude='.git/' --exclude='.cpanel.yml' --exclude='.env.local' --exclude='var/' --exclude='public/uploads/' ./ $DEPLOYPATH
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader --no-interaction
    - cd $DEPLOYPATH && php bin/console cache:clear --env=prod --no-warmup
